name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up environment variables
      env:
        VERSION_SCRIPT: ./.github/workflows/scripts/myscript.sh
    - name: Increment version in .csproj
      run: |
        chmod +x ${{ env.VERSION_SCRIPT }}
        ${{ env.VERSION_SCRIPT }} ./src/SplitBackApi/SplitBackApi.csproj
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal